# Generated by Django 5.0.9 on 2024-10-15 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options_book_author_book_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image',
            new_name='coverImage',
        ),
        migrations.AddField(
            model_name='book',
            name='averageRating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=10000, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publishedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subTitle',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('averageRating__gte', 0), ('averageRating__lte', 5)), name='average_rating_range'),
        ),
    ]
