# Generated by Django 5.0.9 on 2024-10-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_cover_image_book_coverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
