# Generated by Django 5.0.9 on 2024-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subTitle',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
