# Generated by Django 5.0.9 on 2024-10-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
