# Generated by Django 5.0.9 on 2024-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_idgoogle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='idGoogle',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
