# Generated by Django 5.0.9 on 2024-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_idgoogle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Anonymous', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('pending', 'Pending'), ('wishlist', 'Wishlist'), ('discarded', 'Discarded')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='subTitle',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
